GBI-643
rsksmart/rskswap-ui pull request #31
Opened 2022-06-01 13:09 UTC by joaoiovlabs

#Title
Add an awaiter for the transaction to finish and display a message of successfulness (use the toast)

#Description
It was added spinner when user swap token.
It was added error message builder.
it was added success message notification.
It was changed global states and actions.

2022-06-01 13:33 UTC, coolwather commented on src/components/shared/WaitSpinner.vue
> +    <!-- Spinner <div class="spinner-border mb-4" style="height:70px; width:70px"></div> -->
Remove this comment to let the code clean.

2022-06-01 14:53 UTC, aguschirico requested changes
Great work! just a few comments.

2022-06-01 14:53 UTC, aguschirico commented on src/components/swap/SwapBox.vue
> +              deadline: deadline.toString(),
why are you adding this here?

2022-06-01 14:53 UTC, aguschirico commented on src/utils/transactions.ts
> +            `<span>Error: Transaction Info <a class="error-message" href="${url}">${url}</a></span>`
this should open in a new tab, not in the same tab you are in. Please add `target="_blank"` to the anchor.

2022-06-01 14:53 UTC, aguschirico commented on src/components/shared/Notification.vue
> +    message() {
remember we are planning to add at least one test to every PR.

2022-06-02 07:52 UTC, aguschirico approved these changes

2022-06-02 09:40 UTC, merged