[GBI-648] - On focus clear the content and show the place holder
rsksmart/rskswap-ui pull request #36
Opened 2022-06-03 18:17 UTC by manfioLP

https://rsklabs.atlassian.net/browse/GBI-648

https://user-images.githubusercontent.com/19415907/171922888-d827ac9d-d7e9-43d1-8311-6df1bc695b5d.mov

2022-06-03 18:28 UTC, coolwather reviewed
Nice work.
Just about the text I think could be "amount to swap" and in the other field "amount to receive".
For me was kind of weird to have placeholder in only one of the fields.

2022-06-03 19:42 UTC, manfioLP commented
> Nice work. Just about the text I think could be "amount to swap" and in the other field "amount to receive". For me was kind of weird to have placeholder in only one of the fields.

agreed. now that you mentioned it started bugging me as well 😅
 changed it.

2022-06-06 07:47 UTC, aguschirico requested changes
Looks good but please rebase master so we can test everything integrated.

2022-06-06 07:47 UTC, aguschirico commented on src/components/swap/SwapBox.vue
> +              <input placeholder="amount to receive" v-model="swapTo.value" />
At a first sight looks good, but please rebase from main so I can test these changes integrated to the latest ones being merged into main.

2022-06-08 08:10 UTC, merged